import { cn } from '@/lib/utils';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Providers from './components/Providers';
import './globals.css';
const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'AI Chat to Website App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={cn(inter.className, `antialiased min-h-screen`)}>
				<Providers>
					<main className="h-screen text-foreground bg-background">
						{children}
					</main>
				</Providers>
			</body>
		</html>
	);
}
